import { Header } from '@/components/Header';
import './globals.css';
import type { Metadata } from 'next';
import { headerConfig } from '../config';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-primary text-gray-100">
        <Header items={headerConfig} />
        {children}
      </body>
    </html>
  );
}
